$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: weaver-sensitivity-endpoint
model: azureml:sensitivity-classifier:1
code_configuration:
  code: .
  scoring_script: score.py
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
  conda_file: conda.yml
instance_type: Standard_DS2_v2
instance_count: 1
